# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/UnrealEngine

TARGETS = \
	BeerBashers-Android-DebugGame  \
	BeerBashers-Android-Development  \
	BeerBashers-Android-Shipping  \
	BeerBashers-Linux-DebugGame  \
	BeerBashers-Linux-Development  \
	BeerBashers-Linux-Shipping  \
	BeerBashers-LinuxArm64-DebugGame  \
	BeerBashers-LinuxArm64-Development  \
	BeerBashers-LinuxArm64-Shipping  \
	BeerBashers \
	BeerBashersEditor-Linux-DebugGame  \
	BeerBashersEditor-Linux-Development  \
	BeerBashersEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BeerBashersEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BeerBashersEditor-Linux-Debug


BeerBashers-Android-DebugGame:
	 $(BUILD) BeerBashers Android DebugGame  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-Android-Development:
	 $(BUILD) BeerBashers Android Development  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-Android-Shipping:
	 $(BUILD) BeerBashers Android Shipping  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-Linux-DebugGame:
	 $(BUILD) BeerBashers Linux DebugGame  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-Linux-Development:
	 $(BUILD) BeerBashers Linux Development  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-Linux-Shipping:
	 $(BUILD) BeerBashers Linux Shipping  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-LinuxArm64-DebugGame:
	 $(BUILD) BeerBashers LinuxArm64 DebugGame  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-LinuxArm64-Development:
	 $(BUILD) BeerBashers LinuxArm64 Development  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers-LinuxArm64-Shipping:
	 $(BUILD) BeerBashers LinuxArm64 Shipping  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashers: BeerBashers-Linux-Development

BeerBashersEditor-Linux-DebugGame:
	 $(BUILD) BeerBashersEditor Linux DebugGame  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashersEditor-Linux-Development:
	 $(BUILD) BeerBashersEditor Linux Development  -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" $(ARGS)

BeerBashersEditor: BeerBashersEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/teapotexpress/Documents/Unreal Projects/BeerBashers/BeerBashers.uproject" -Game 

.PHONY: $(TARGETS)
